### ISSUE TITLE
Rule "Required if" in loops don't work

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#754] opened 2020-06-02 21:53 UTC
When assigning a"Required if" rule to a field inside a loop, the rule does not work, when the parent field is outside of the loop control.

**Comment by sanjacornelius** [comment] 2020-06-22 15:24
This is a duplicate of this closed issue https://github.com/ProcessMaker/screen-builder/issues/746

**Comment by PMQABen** [comment] 2020-06-22 18:37
Use `_parent.VARIABLE_NAME` to reference a variable outside of the loop when running validations.

https://www.loom.com/share/42bb06fd04b04d0a92c5028d2c8351d6

**Closed by PMQABen** 2020-06-22 18:37 UTC
Labels: P1, bug
