### ISSUE TITLE
Deleting a watcher deletes all watchers

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#555] opened 2020-02-24 04:53 UTC
Create a screen, add two or more watchers

Save the screen and reload the page

Run the screen in preview, allow the watcher to complete

Go back to the design page, choose watchers

Delete any of the watchers

**Result:**

All watchers are deleted

**Expected:**

Only the specified watcher to be deleted is removed.

**Comment by nolanpro** [comment] 2020-02-26 22:30
@velkymx Ryan and I can't reproduce the issue. Might have been fixed as part of another issue. Following each step, only the correct watcher is deleted.

**Comment by PMQABen** [comment] 2020-02-27 21:11
Same, can't reproduce this in 4.0.3dev. I think we can probably close this ticket.

**Comment by ZLTM** [comment] 2020-02-28 12:09
Cant reproduce on 4.0.3, however, it did it reproduced on 4.0.2, looks like it has been fixed

**Comment by ZLTM** [comment] 2020-02-28 12:40
Can't reproduce on 4.0.3

**Closed** 2020-03-02 16:56 UTC
Labels: bug, cant reproduce
