### ISSUE TITLE
Record List can be submitted with Validation Issues

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#713] opened 2020-05-13 15:09 UTC
Steps to Reproduce:

Add a form to add to a record list
add validation to the record list form fields
go to the preview and try and add records to the record list
Validation fires, form is saved. 

Expected behavior

Validation fires. Form does NOT save until validation is satisfied.

**Comment by nolanpro** [comment] 2020-05-13 16:29
Can only reproduce when editing. Not able to reproduce when adding like in the steps. Validation prevents modal from closing: 
![Kapture 2020-05-13 at 9 27 52](https://user-images.githubusercontent.com/2546850/81839187-0ed91a80-94fc-11ea-846d-487d7fab38ef.gif)

**Closed** 2020-05-13 20:47 UTC
Labels: bug, review

**Comment by ZLTM** [comment] 2020-05-14 20:51
The validation rules are being validated, however, the data type is not
https://www.dropbox.com/s/fd312ltcbaw6e1f/2020-05-14%2016-41-25.mp4?dl=0

the bug is reported on Jira
https://processmaker.atlassian.net/browse/FOUR-1472
