### ISSUE TITLE
Server Side Rendering Fails

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#308] opened 2019-07-29 16:38 UTC
See: https://github.com/ProcessMaker/connector-send-email/issues/33

**Comment by chipit24** [comment] 2019-07-31 16:12
@nolanpro We've updated `screen-builder` and `vue-form-elements` to "protect" against any references to window (using `typeof window !== 'undefined'`), but we're running into a strange issue. When running `php test.php` we get the following error:

```console
webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:70114
}(window));
  ^

ReferenceError: window is not defined
    at eval (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:70114:3)
    at Object.e562 (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:70115:3)
    at __webpack_require__ (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:21:30)
    at Module.fb15 (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:72086:15)
    at __webpack_require__ (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:21:30)
    at eval (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:85:18)
    at eval (webpack:////Users/***/Code/vue-form-elements/dist/vue-form-elements.common.js?:88:10)
    at Object.../../../../vue-form-elements/dist/vue-form-elements.common.js (/private/tmp/a274d5de5a328d34cbaf031597760468.js:121:1)
    at __webpack_require__ (/private/tmp/a274d5de5a328d34cbaf031597760468.js:22:30)
    at Object.2ac6 (webpack:////Users/***/Code/screen-builder/dist/vue-form-builder.common.js?:12694:18)
 in /Users/***/Code/connector-send-email/resources/js/ssr/tests/vendor/symfony/process/Process.php on line 256
```

It seems the issue is coming from the `vue-form-elements` build. What's strange, is that even if we remove all references to `window` and set `target: 'node'` in the webpack config for `vue-form-elements`, it still includes that window reference in the output.

**Comment by chipit24** [comment] 2019-08-01 14:05
@velkymx We've spend a significant amount of time trying to resolve the above issue without resolve. How would you like us to prioritize this issue? SSR is working with the previous versions of screen-builder, so it seems this is a new feature as opposed to a bug.

**Comment by tdondich** [comment] 2019-08-01 14:18
Are you saying SSR is working as intended, but the test is failing?

**Comment by chipit24** [comment] 2019-08-01 14:23
It's working as intended and the test pass _before_ we update screen-builder, but breaks when we update screen-builder. Our concern is that we've already spend a lot of time debugging this, and with the release coming up we'd like to know if this should be re-prioritized so we can work on other bugs, or if we should keep hammering away at this.

**Comment by nolanpro** [comment] 2019-08-06 00:25
@chipit24 @velkymx Got it to render but it still needs some work and I don't know the best way to finish this up. Aside from the several global window references (fixed in this branch and vue-form-elements branch), the problem was tinymce was using the global window object.

1. In vue-form-elements#feature/58, I globally ignore all tinymce in the [new file vue.config.js](https://github.com/ProcessMaker/vue-form-elements/blob/feature/58/vue.config.js). Of course this won't work for the app so we need to figure out a way to run build separate targets in /dist. Maybe like this: https://webpack.js.org/concepts/targets/#multiple-targets

2. I had to add [a bunch of dummy files in connector-send-email#bugfix/33](https://github.com/ProcessMaker/connector-send-email/tree/bugfix/33/resources/js/ssr/src/dummies) so it wouldn't complain about all the tinymce files we ignored. Do these files actually need to exist or is there some way to just ignore them or have them all point to one dummy file?

3. The record list isn't working for some reason [when running the test](https://github.com/ProcessMaker/connector-send-email/blob/bugfix/33/resources/js/ssr/tests/test.js). It still says "No Data Available". I suspect it has to do with the recent chances to the record list source settings. It's using the custom FormRecordListStatic component since we had problems getting vuetable to output any data in SSR due to its async nature. Maybe we can revisit that since it will be a pain to maintain the separate static renderer.

4. I had to add a [custom tinymce renderer](https://github.com/ProcessMaker/connector-send-email/blob/bugfix/33/resources/js/ssr/src/rich-text-component.js) to output the html and alias it in the webpack config. Maybe this can be a custom renderer the same way we do FormRecordListStatic

**Comment by chipit24** [comment] 2019-08-06 13:27
@nolanpro Good find! Thank you!

1. Setting up externals is something we do in other packages for peer dependencies. This doesn't ignore the package, but sets it up in a way that the app still requires the package, but just expects it to exist externally. To truly ignore it, we'd have to make sure the app doesn't actually still rely on the package.

   This seems a bit counterintuitive though, since the whole reason for updating `screen-builder` and `vue-form-elements` was to get access to new form elements like the rich text editor / html editor. If `tinymce` wasn't built to accommodate SSR then this is a huge issue. We'd have to fork `tinymce` and put in some work to get it to work with SSR, and then maybe those changes can be brought back into the `tinymce` repo through a PR.

2. Yes. `tinymce` won't be bundled, but it's still required by the rich text editor which expects it to be accessible. The only way around this is to make `tinymce` play nicely with SSR, or to create an SSR version of the rich text editor which doesn't rely on `tinymce`.

**Comment by velkymx** [comment] 2019-08-06 15:54
FYI for the email screen type the Rich Text is render only. You cannot enable Rich Text on the screen like you can in a form.

**Comment by chipit24** [comment] 2019-08-06 17:55
@nolanpro I got it working using dynamic imports and async components without having to set up externals or dummy files. With this setup, the standalone apps still work with `tinymce`, and it builds without issue in SSR, with `php test.php` passing. I'll have PRs up for review in a bit.

For reference:
https://webpack.js.org/guides/code-splitting/#dynamic-imports
https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components

**Closed** 2019-08-07 15:22 UTC
Labels: P0, WIP, bug
