### ISSUE TITLE
Record list: Uploads

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#764] opened 2020-06-22 14:47 UTC
*Description*

1. Create a Screen with an editable record list control and a separate record list page
2. On the list page, add a checkbox and two file upload controls
3. Add a visibility rule to one of the two file uploads so it only displays when the checkbox is clicked
4. Save and run as part of a Process
5. Click to add a record list, then upload a file to the first displayed file upload controller
6. Click the checkbox, then upload a file to the second upload controller
7. Save and notice the record list

**Result:**
Only one of the two filenames are populated in the record list. Video available.

**Comment by sanjacornelius** [comment] 2020-06-22 15:28
Duplicate of closed issue https://github.com/ProcessMaker/screen-builder/issues/752

**Closed** 2020-07-02 14:18 UTC
Labels: P1, bug
